### ISSUE TITLE
config.is_dlib = True config.is_mp = False

### ISSUE THREAD

**Issue by sunjunlishi** [shubhajitbasak/3DFaceLight#1]
but got an unexpected keyword argument 'model_selection'

Traceback (most recent call last):
  File "inference.py", line 160, in <module>
    main(args.configfile)
  File "inference.py", line 62, in main
    vertices = process_input_mp(img_path, net, mp_face_detection, cuda=isGPU)
  File "/data1/sun_train/3DFaceLight-main/MyTest/utils/utils_inference.py", line 451, in process_input_mp
    left, right, top, bottom = get_rect_mp(image, mp_face_detection)
  File "/data1/sun_train/3DFaceLight-main/MyTest/utils/utils_inference.py", line 377, in get_rect_mp
    model_selection=0, min_detection_confidence=0.5) as face_detection:
TypeError: __init__() got an unexpected keyword argument 'model_selection'

**Comment by sunjunlishi** [comment]
mediapipe version so  mp_face_detection.FaceDetection();
and inference.py :
  for idex in range(9):
                kpt_filter[4+idex]=499
vertices is 500

**Comment by sunjunlishi** [comment]
result
![微信图片_20221022162835](https://user-images.githubusercontent.com/11845664/197329949-9e3b24d6-3ec9-4f83-a824-4f4b6c62c1dc.png)
![微信图片_20221022163632](https://user-images.githubusercontent.com/11845664/197329955-a87c90b5-39ce-4fec-a091-ea4d4f6d5dc8.png)
![微信图片_20221022163658](https://user-images.githubusercontent.com/11845664/197329962-c8a731d4-f852-406f-91b6-f923dc7c52bf.png)
